// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.TypeChambre type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeChambre type = 2;</code>
   * @return The type.
   */
  ma.projet.api.stubs.TypeChambre getType();

  /**
   * <code>float prix = 3;</code>
   * @return The prix.
   */
  float getPrix();

  /**
   * <code>bool disponible = 4;</code>
   * @return The disponible.
   */
  boolean getDisponible();

  /**
   * <code>repeated .Reservation reservations = 5;</code>
   */
  java.util.List<ma.projet.api.stubs.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .Reservation reservations = 5;</code>
   */
  ma.projet.api.stubs.Reservation getReservations(int index);
  /**
   * <code>repeated .Reservation reservations = 5;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .Reservation reservations = 5;</code>
   */
  java.util.List<? extends ma.projet.api.stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .Reservation reservations = 5;</code>
   */
  ma.projet.api.stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
