// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetAllClientsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllClientsRequest)
    com.google.protobuf.MessageOrBuilder {
}
