// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetAllChambresRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllChambresRequest)
    com.google.protobuf.MessageOrBuilder {
}
