// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetAllClientsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllClientsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<ma.projet.api.stubs.Client> 
      getClientsList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  ma.projet.api.stubs.Client getClients(int index);
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<? extends ma.projet.api.stubs.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  ma.projet.api.stubs.ClientOrBuilder getClientsOrBuilder(
      int index);
}
