// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetAllChambresResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllChambresResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<ma.projet.api.stubs.Chambre> 
      getChambresList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  ma.projet.api.stubs.Chambre getChambres(int index);
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  int getChambresCount();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<? extends ma.projet.api.stubs.ChambreOrBuilder> 
      getChambresOrBuilderList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  ma.projet.api.stubs.ChambreOrBuilder getChambresOrBuilder(
      int index);
}
