// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

/**
 * Protobuf type {@code GetAllUtilisateursResponse}
 */
public  final class GetAllUtilisateursResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllUtilisateursResponse)
    GetAllUtilisateursResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllUtilisateursResponse.newBuilder() to construct.
  private GetAllUtilisateursResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllUtilisateursResponse() {
    utilisateurs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllUtilisateursResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllUtilisateursResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              utilisateurs_ = new java.util.ArrayList<ma.projet.api.stubs.Utilisateur>();
              mutable_bitField0_ |= 0x00000001;
            }
            utilisateurs_.add(
                input.readMessage(ma.projet.api.stubs.Utilisateur.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        utilisateurs_ = java.util.Collections.unmodifiableList(utilisateurs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ma.projet.api.stubs.ReservationServiceOuterClass.internal_static_GetAllUtilisateursResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ma.projet.api.stubs.ReservationServiceOuterClass.internal_static_GetAllUtilisateursResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ma.projet.api.stubs.GetAllUtilisateursResponse.class, ma.projet.api.stubs.GetAllUtilisateursResponse.Builder.class);
  }

  public static final int UTILISATEURS_FIELD_NUMBER = 1;
  private java.util.List<ma.projet.api.stubs.Utilisateur> utilisateurs_;
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  public java.util.List<ma.projet.api.stubs.Utilisateur> getUtilisateursList() {
    return utilisateurs_;
  }
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  public java.util.List<? extends ma.projet.api.stubs.UtilisateurOrBuilder> 
      getUtilisateursOrBuilderList() {
    return utilisateurs_;
  }
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  public int getUtilisateursCount() {
    return utilisateurs_.size();
  }
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  public ma.projet.api.stubs.Utilisateur getUtilisateurs(int index) {
    return utilisateurs_.get(index);
  }
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  public ma.projet.api.stubs.UtilisateurOrBuilder getUtilisateursOrBuilder(
      int index) {
    return utilisateurs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < utilisateurs_.size(); i++) {
      output.writeMessage(1, utilisateurs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < utilisateurs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, utilisateurs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ma.projet.api.stubs.GetAllUtilisateursResponse)) {
      return super.equals(obj);
    }
    ma.projet.api.stubs.GetAllUtilisateursResponse other = (ma.projet.api.stubs.GetAllUtilisateursResponse) obj;

    if (!getUtilisateursList()
        .equals(other.getUtilisateursList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUtilisateursCount() > 0) {
      hash = (37 * hash) + UTILISATEURS_FIELD_NUMBER;
      hash = (53 * hash) + getUtilisateursList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.api.stubs.GetAllUtilisateursResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ma.projet.api.stubs.GetAllUtilisateursResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllUtilisateursResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllUtilisateursResponse)
      ma.projet.api.stubs.GetAllUtilisateursResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.projet.api.stubs.ReservationServiceOuterClass.internal_static_GetAllUtilisateursResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.projet.api.stubs.ReservationServiceOuterClass.internal_static_GetAllUtilisateursResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.projet.api.stubs.GetAllUtilisateursResponse.class, ma.projet.api.stubs.GetAllUtilisateursResponse.Builder.class);
    }

    // Construct using ma.projet.api.stubs.GetAllUtilisateursResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUtilisateursFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (utilisateursBuilder_ == null) {
        utilisateurs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        utilisateursBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ma.projet.api.stubs.ReservationServiceOuterClass.internal_static_GetAllUtilisateursResponse_descriptor;
    }

    @java.lang.Override
    public ma.projet.api.stubs.GetAllUtilisateursResponse getDefaultInstanceForType() {
      return ma.projet.api.stubs.GetAllUtilisateursResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ma.projet.api.stubs.GetAllUtilisateursResponse build() {
      ma.projet.api.stubs.GetAllUtilisateursResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ma.projet.api.stubs.GetAllUtilisateursResponse buildPartial() {
      ma.projet.api.stubs.GetAllUtilisateursResponse result = new ma.projet.api.stubs.GetAllUtilisateursResponse(this);
      int from_bitField0_ = bitField0_;
      if (utilisateursBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          utilisateurs_ = java.util.Collections.unmodifiableList(utilisateurs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.utilisateurs_ = utilisateurs_;
      } else {
        result.utilisateurs_ = utilisateursBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ma.projet.api.stubs.GetAllUtilisateursResponse) {
        return mergeFrom((ma.projet.api.stubs.GetAllUtilisateursResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ma.projet.api.stubs.GetAllUtilisateursResponse other) {
      if (other == ma.projet.api.stubs.GetAllUtilisateursResponse.getDefaultInstance()) return this;
      if (utilisateursBuilder_ == null) {
        if (!other.utilisateurs_.isEmpty()) {
          if (utilisateurs_.isEmpty()) {
            utilisateurs_ = other.utilisateurs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUtilisateursIsMutable();
            utilisateurs_.addAll(other.utilisateurs_);
          }
          onChanged();
        }
      } else {
        if (!other.utilisateurs_.isEmpty()) {
          if (utilisateursBuilder_.isEmpty()) {
            utilisateursBuilder_.dispose();
            utilisateursBuilder_ = null;
            utilisateurs_ = other.utilisateurs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            utilisateursBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUtilisateursFieldBuilder() : null;
          } else {
            utilisateursBuilder_.addAllMessages(other.utilisateurs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ma.projet.api.stubs.GetAllUtilisateursResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ma.projet.api.stubs.GetAllUtilisateursResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ma.projet.api.stubs.Utilisateur> utilisateurs_ =
      java.util.Collections.emptyList();
    private void ensureUtilisateursIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        utilisateurs_ = new java.util.ArrayList<ma.projet.api.stubs.Utilisateur>(utilisateurs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ma.projet.api.stubs.Utilisateur, ma.projet.api.stubs.Utilisateur.Builder, ma.projet.api.stubs.UtilisateurOrBuilder> utilisateursBuilder_;

    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public java.util.List<ma.projet.api.stubs.Utilisateur> getUtilisateursList() {
      if (utilisateursBuilder_ == null) {
        return java.util.Collections.unmodifiableList(utilisateurs_);
      } else {
        return utilisateursBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public int getUtilisateursCount() {
      if (utilisateursBuilder_ == null) {
        return utilisateurs_.size();
      } else {
        return utilisateursBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public ma.projet.api.stubs.Utilisateur getUtilisateurs(int index) {
      if (utilisateursBuilder_ == null) {
        return utilisateurs_.get(index);
      } else {
        return utilisateursBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder setUtilisateurs(
        int index, ma.projet.api.stubs.Utilisateur value) {
      if (utilisateursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUtilisateursIsMutable();
        utilisateurs_.set(index, value);
        onChanged();
      } else {
        utilisateursBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder setUtilisateurs(
        int index, ma.projet.api.stubs.Utilisateur.Builder builderForValue) {
      if (utilisateursBuilder_ == null) {
        ensureUtilisateursIsMutable();
        utilisateurs_.set(index, builderForValue.build());
        onChanged();
      } else {
        utilisateursBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder addUtilisateurs(ma.projet.api.stubs.Utilisateur value) {
      if (utilisateursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUtilisateursIsMutable();
        utilisateurs_.add(value);
        onChanged();
      } else {
        utilisateursBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder addUtilisateurs(
        int index, ma.projet.api.stubs.Utilisateur value) {
      if (utilisateursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUtilisateursIsMutable();
        utilisateurs_.add(index, value);
        onChanged();
      } else {
        utilisateursBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder addUtilisateurs(
        ma.projet.api.stubs.Utilisateur.Builder builderForValue) {
      if (utilisateursBuilder_ == null) {
        ensureUtilisateursIsMutable();
        utilisateurs_.add(builderForValue.build());
        onChanged();
      } else {
        utilisateursBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder addUtilisateurs(
        int index, ma.projet.api.stubs.Utilisateur.Builder builderForValue) {
      if (utilisateursBuilder_ == null) {
        ensureUtilisateursIsMutable();
        utilisateurs_.add(index, builderForValue.build());
        onChanged();
      } else {
        utilisateursBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder addAllUtilisateurs(
        java.lang.Iterable<? extends ma.projet.api.stubs.Utilisateur> values) {
      if (utilisateursBuilder_ == null) {
        ensureUtilisateursIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, utilisateurs_);
        onChanged();
      } else {
        utilisateursBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder clearUtilisateurs() {
      if (utilisateursBuilder_ == null) {
        utilisateurs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        utilisateursBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public Builder removeUtilisateurs(int index) {
      if (utilisateursBuilder_ == null) {
        ensureUtilisateursIsMutable();
        utilisateurs_.remove(index);
        onChanged();
      } else {
        utilisateursBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public ma.projet.api.stubs.Utilisateur.Builder getUtilisateursBuilder(
        int index) {
      return getUtilisateursFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public ma.projet.api.stubs.UtilisateurOrBuilder getUtilisateursOrBuilder(
        int index) {
      if (utilisateursBuilder_ == null) {
        return utilisateurs_.get(index);  } else {
        return utilisateursBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public java.util.List<? extends ma.projet.api.stubs.UtilisateurOrBuilder> 
         getUtilisateursOrBuilderList() {
      if (utilisateursBuilder_ != null) {
        return utilisateursBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(utilisateurs_);
      }
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public ma.projet.api.stubs.Utilisateur.Builder addUtilisateursBuilder() {
      return getUtilisateursFieldBuilder().addBuilder(
          ma.projet.api.stubs.Utilisateur.getDefaultInstance());
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public ma.projet.api.stubs.Utilisateur.Builder addUtilisateursBuilder(
        int index) {
      return getUtilisateursFieldBuilder().addBuilder(
          index, ma.projet.api.stubs.Utilisateur.getDefaultInstance());
    }
    /**
     * <code>repeated .Utilisateur utilisateurs = 1;</code>
     */
    public java.util.List<ma.projet.api.stubs.Utilisateur.Builder> 
         getUtilisateursBuilderList() {
      return getUtilisateursFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ma.projet.api.stubs.Utilisateur, ma.projet.api.stubs.Utilisateur.Builder, ma.projet.api.stubs.UtilisateurOrBuilder> 
        getUtilisateursFieldBuilder() {
      if (utilisateursBuilder_ == null) {
        utilisateursBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ma.projet.api.stubs.Utilisateur, ma.projet.api.stubs.Utilisateur.Builder, ma.projet.api.stubs.UtilisateurOrBuilder>(
                utilisateurs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        utilisateurs_ = null;
      }
      return utilisateursBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllUtilisateursResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllUtilisateursResponse)
  private static final ma.projet.api.stubs.GetAllUtilisateursResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ma.projet.api.stubs.GetAllUtilisateursResponse();
  }

  public static ma.projet.api.stubs.GetAllUtilisateursResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllUtilisateursResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllUtilisateursResponse>() {
    @java.lang.Override
    public GetAllUtilisateursResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllUtilisateursResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllUtilisateursResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllUtilisateursResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ma.projet.api.stubs.GetAllUtilisateursResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

