// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetAllUtilisateursResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllUtilisateursResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  java.util.List<ma.projet.api.stubs.Utilisateur> 
      getUtilisateursList();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  ma.projet.api.stubs.Utilisateur getUtilisateurs(int index);
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  int getUtilisateursCount();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  java.util.List<? extends ma.projet.api.stubs.UtilisateurOrBuilder> 
      getUtilisateursOrBuilderList();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  ma.projet.api.stubs.UtilisateurOrBuilder getUtilisateursOrBuilder(
      int index);
}
