// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetChambreByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetChambreByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Chambre chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   * @return The chambre.
   */
  ma.projet.api.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   */
  ma.projet.api.stubs.ChambreOrBuilder getChambreOrBuilder();
}
