// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface GetUtilisateurByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUtilisateurByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   * @return Whether the utilisateur field is set.
   */
  boolean hasUtilisateur();
  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   * @return The utilisateur.
   */
  ma.projet.api.stubs.Utilisateur getUtilisateur();
  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   */
  ma.projet.api.stubs.UtilisateurOrBuilder getUtilisateurOrBuilder();
}
