// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public final class ReservationServiceOuterClass {
  private ReservationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utilisateur_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utilisateur_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UtilisateurRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UtilisateurRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUtilisateurByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUtilisateurByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUtilisateurByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUtilisateurByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveUtilisateurRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveUtilisateurRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveUtilisateurResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveUtilisateurResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteUtilisateurRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteUtilisateurRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteUtilisateurResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteUtilisateurResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUtilisateursRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllUtilisateursRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUtilisateursResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllUtilisateursResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ReservationService.proto\"S\n\006Client\022\n\n\002" +
      "id\030\001 \001(\t\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030\003 \001(\t\022\r\n" +
      "\005email\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"N\n\rClien" +
      "tRequest\022\013\n\003nom\030\001 \001(\t\022\016\n\006prenom\030\002 \001(\t\022\r\n" +
      "\005email\030\003 \001(\t\022\021\n\ttelephone\030\004 \001(\t\"w\n\007Chamb" +
      "re\022\n\n\002id\030\001 \001(\t\022\032\n\004type\030\002 \001(\0162\014.TypeChamb" +
      "re\022\014\n\004prix\030\003 \001(\002\022\022\n\ndisponible\030\004 \001(\010\022\"\n\014" +
      "reservations\030\005 \003(\0132\014.Reservation\"N\n\016Cham" +
      "breRequest\022\032\n\004type\030\001 \001(\0162\014.TypeChambre\022\014" +
      "\n\004prix\030\002 \001(\002\022\022\n\ndisponible\030\003 \001(\010\"O\n\013Util" +
      "isateur\022\n\n\002id\030\001 \001(\t\022\013\n\003nom\030\002 \001(\t\022\022\n\nmotD" +
      "ePasse\030\003 \001(\t\022\023\n\004role\030\004 \001(\0162\005.Role\"J\n\022Uti" +
      "lisateurRequest\022\013\n\003nom\030\001 \001(\t\022\022\n\nmotDePas" +
      "se\030\002 \001(\t\022\023\n\004role\030\003 \001(\0162\005.Role\"\206\001\n\013Reserv" +
      "ation\022\n\n\002id\030\001 \001(\t\022\021\n\tdateDebut\030\002 \001(\t\022\017\n\007" +
      "dateFin\030\003 \001(\t\022\023\n\013preferences\030\004 \001(\t\022\027\n\006cl" +
      "ient\030\005 \001(\0132\007.Client\022\031\n\007chambre\030\006 \001(\0132\010.C" +
      "hambre\"r\n\022ReservationRequest\022\021\n\tdateDebu" +
      "t\030\001 \001(\t\022\017\n\007dateFin\030\002 \001(\t\022\023\n\013preferences\030" +
      "\003 \001(\t\022\020\n\010clientId\030\004 \001(\t\022\021\n\tchambreId\030\005 \001" +
      "(\t\"\026\n\024GetAllClientsRequest\"1\n\025GetAllClie" +
      "ntsResponse\022\030\n\007clients\030\001 \003(\0132\007.Client\"\"\n" +
      "\024GetClientByIdRequest\022\n\n\002id\030\001 \001(\t\"0\n\025Get" +
      "ClientByIdResponse\022\027\n\006client\030\001 \001(\0132\007.Cli" +
      "ent\"3\n\021SaveClientRequest\022\036\n\006client\030\001 \001(\013" +
      "2\016.ClientRequest\"-\n\022SaveClientResponse\022\027" +
      "\n\006client\030\001 \001(\0132\007.Client\"!\n\023DeleteClientR" +
      "equest\022\n\n\002id\030\001 \001(\t\"\'\n\024DeleteClientRespon" +
      "se\022\017\n\007success\030\001 \001(\010\"#\n\025GetChambreByIdReq" +
      "uest\022\n\n\002id\030\001 \001(\t\"3\n\026GetChambreByIdRespon" +
      "se\022\031\n\007chambre\030\001 \001(\0132\010.Chambre\"6\n\022SaveCha" +
      "mbreRequest\022 \n\007chambre\030\001 \001(\0132\017.ChambreRe" +
      "quest\"0\n\023SaveChambreResponse\022\031\n\007chambre\030" +
      "\001 \001(\0132\010.Chambre\"\"\n\024DeleteChambreRequest\022" +
      "\n\n\002id\030\001 \001(\t\"(\n\025DeleteChambreResponse\022\017\n\007" +
      "success\030\001 \001(\010\"\'\n\031GetUtilisateurByIdReque" +
      "st\022\n\n\002id\030\001 \001(\t\"?\n\032GetUtilisateurByIdResp" +
      "onse\022!\n\013utilisateur\030\001 \001(\0132\014.Utilisateur\"" +
      "B\n\026SaveUtilisateurRequest\022(\n\013utilisateur" +
      "\030\001 \001(\0132\023.UtilisateurRequest\"<\n\027SaveUtili" +
      "sateurResponse\022!\n\013utilisateur\030\001 \001(\0132\014.Ut" +
      "ilisateur\"&\n\030DeleteUtilisateurRequest\022\n\n" +
      "\002id\030\001 \001(\t\",\n\031DeleteUtilisateurResponse\022\017" +
      "\n\007success\030\001 \001(\010\"\'\n\031GetReservationByIdReq" +
      "uest\022\n\n\002id\030\001 \001(\t\"?\n\032GetReservationByIdRe" +
      "sponse\022!\n\013reservation\030\001 \001(\0132\014.Reservatio" +
      "n\"B\n\026SaveReservationRequest\022(\n\013reservati" +
      "on\030\001 \001(\0132\023.ReservationRequest\"<\n\027SaveRes" +
      "ervationResponse\022!\n\013reservation\030\001 \001(\0132\014." +
      "Reservation\"&\n\030DeleteReservationRequest\022" +
      "\n\n\002id\030\001 \001(\t\",\n\031DeleteReservationResponse" +
      "\022\017\n\007success\030\001 \001(\010\"\033\n\031GetAllUtilisateursR" +
      "equest\"@\n\032GetAllUtilisateursResponse\022\"\n\014" +
      "utilisateurs\030\001 \003(\0132\014.Utilisateur\"\033\n\031GetA" +
      "llReservationsRequest\"@\n\032GetAllReservati" +
      "onsResponse\022\"\n\014reservations\030\001 \003(\0132\014.Rese" +
      "rvation\"\027\n\025GetAllChambresRequest\"4\n\026GetA" +
      "llChambresResponse\022\032\n\010chambres\030\001 \003(\0132\010.C" +
      "hambre*%\n\013TypeChambre\022\n\n\006SIMPLE\020\000\022\n\n\006DOU" +
      "BLE\020\001*+\n\004Role\022\017\n\013UTILISATEUR\020\000\022\022\n\016ADMINI" +
      "STRATEUR\020\0012\375\001\n\rClientService\022;\n\nAllClien" +
      "ts\022\025.GetAllClientsRequest\032\026.GetAllClient" +
      "sResponse\022;\n\nClientById\022\025.GetClientByIdR" +
      "equest\032\026.GetClientByIdResponse\0225\n\nSaveCl" +
      "ient\022\022.SaveClientRequest\032\023.SaveClientRes" +
      "ponse\022;\n\014deleteClient\022\024.DeleteClientRequ" +
      "est\032\025.DeleteClientResponse2\212\002\n\016ChambreSe" +
      "rvice\022>\n\013AllChambres\022\026.GetAllChambresReq" +
      "uest\032\027.GetAllChambresResponse\022>\n\013Chambre" +
      "ById\022\026.GetChambreByIdRequest\032\027.GetChambr" +
      "eByIdResponse\0228\n\013SaveChambre\022\023.SaveChamb" +
      "reRequest\032\024.SaveChambreResponse\022>\n\rdelet" +
      "eChambre\022\025.DeleteChambreRequest\032\026.Delete" +
      "ChambreResponse2\276\002\n\022UtilisateurService\022J" +
      "\n\017AllUtilisateurs\022\032.GetAllUtilisateursRe" +
      "quest\032\033.GetAllUtilisateursResponse\022J\n\017Ut" +
      "ilisateurById\022\032.GetUtilisateurByIdReques" +
      "t\032\033.GetUtilisateurByIdResponse\022D\n\017SaveUt" +
      "ilisateur\022\027.SaveUtilisateurRequest\032\030.Sav" +
      "eUtilisateurResponse\022J\n\021deleteUtilisateu" +
      "r\022\031.DeleteUtilisateurRequest\032\032.DeleteUti" +
      "lisateurResponse2\276\002\n\022ReservationService\022" +
      "J\n\017AllReservations\022\032.GetAllReservationsR" +
      "equest\032\033.GetAllReservationsResponse\022J\n\017R" +
      "eservationById\022\032.GetReservationByIdReque" +
      "st\032\033.GetReservationByIdResponse\022D\n\017SaveR" +
      "eservation\022\027.SaveReservationRequest\032\030.Sa" +
      "veReservationResponse\022J\n\021deleteReservati" +
      "on\022\031.DeleteReservationRequest\032\032.DeleteRe" +
      "servationResponseB\027\n\023ma.projet.api.stubs" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientRequest_descriptor,
        new java.lang.String[] { "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", "Reservations", });
    internal_static_ChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreRequest_descriptor,
        new java.lang.String[] { "Type", "Prix", "Disponible", });
    internal_static_Utilisateur_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Utilisateur_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utilisateur_descriptor,
        new java.lang.String[] { "Id", "Nom", "MotDePasse", "Role", });
    internal_static_UtilisateurRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UtilisateurRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UtilisateurRequest_descriptor,
        new java.lang.String[] { "Nom", "MotDePasse", "Role", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "DateDebut", "DateFin", "Preferences", "Client", "Chambre", });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "DateDebut", "DateFin", "Preferences", "ClientId", "ChambreId", });
    internal_static_GetAllClientsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetAllClientsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllClientsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GetAllClientsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsResponse_descriptor,
        new java.lang.String[] { "Clients", });
    internal_static_GetClientByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GetClientByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetClientByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetClientByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientByIdResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_SaveClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_SaveClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveClientRequest_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_SaveClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_SaveClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveClientResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_DeleteClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_DeleteClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_DeleteClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetChambreByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_GetChambreByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetChambreByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_GetChambreByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreByIdResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_SaveChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_SaveChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveChambreRequest_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_SaveChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_SaveChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveChambreResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_DeleteChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_DeleteChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_DeleteChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetUtilisateurByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_GetUtilisateurByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUtilisateurByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetUtilisateurByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_GetUtilisateurByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUtilisateurByIdResponse_descriptor,
        new java.lang.String[] { "Utilisateur", });
    internal_static_SaveUtilisateurRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_SaveUtilisateurRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveUtilisateurRequest_descriptor,
        new java.lang.String[] { "Utilisateur", });
    internal_static_SaveUtilisateurResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_SaveUtilisateurResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveUtilisateurResponse_descriptor,
        new java.lang.String[] { "Utilisateur", });
    internal_static_DeleteUtilisateurRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_DeleteUtilisateurRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteUtilisateurRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteUtilisateurResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_DeleteUtilisateurResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteUtilisateurResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_SaveReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_SaveReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetAllUtilisateursRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_GetAllUtilisateursRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllUtilisateursRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllUtilisateursResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_GetAllUtilisateursResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllUtilisateursResponse_descriptor,
        new java.lang.String[] { "Utilisateurs", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetAllChambresRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_GetAllChambresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllChambresResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_GetAllChambresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresResponse_descriptor,
        new java.lang.String[] { "Chambres", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
