// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface SaveUtilisateurRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveUtilisateurRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UtilisateurRequest utilisateur = 1;</code>
   * @return Whether the utilisateur field is set.
   */
  boolean hasUtilisateur();
  /**
   * <code>.UtilisateurRequest utilisateur = 1;</code>
   * @return The utilisateur.
   */
  ma.projet.api.stubs.UtilisateurRequest getUtilisateur();
  /**
   * <code>.UtilisateurRequest utilisateur = 1;</code>
   */
  ma.projet.api.stubs.UtilisateurRequestOrBuilder getUtilisateurOrBuilder();
}
