// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface SaveClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientRequest client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ClientRequest client = 1;</code>
   * @return The client.
   */
  ma.projet.api.stubs.ClientRequest getClient();
  /**
   * <code>.ClientRequest client = 1;</code>
   */
  ma.projet.api.stubs.ClientRequestOrBuilder getClientOrBuilder();
}
