// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface SaveClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  ma.projet.api.stubs.Client getClient();
  /**
   * <code>.Client client = 1;</code>
   */
  ma.projet.api.stubs.ClientOrBuilder getClientOrBuilder();
}
