// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface SaveReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  ma.projet.api.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  ma.projet.api.stubs.ReservationOrBuilder getReservationOrBuilder();
}
