// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package ma.projet.api.stubs;

public interface UtilisateurRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UtilisateurRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nom = 1;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 1;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string motDePasse = 2;</code>
   * @return The motDePasse.
   */
  java.lang.String getMotDePasse();
  /**
   * <code>string motDePasse = 2;</code>
   * @return The bytes for motDePasse.
   */
  com.google.protobuf.ByteString
      getMotDePasseBytes();

  /**
   * <code>.Role role = 3;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.Role role = 3;</code>
   * @return The role.
   */
  ma.projet.api.stubs.Role getRole();
}
